name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-05"


[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiODYyMDQ0OTEtNTkyNi00NjU5LThmMGYtZTA0YzQ1MWI1NzBiIiwidGVuYW50X2lkIjoiMjMzZGY1ZDVhYjJkN2Y5YWEzOGNkODZhOTVkMWE1OWIzMDFkOWNkMDA4ZjVhM2E5NzBmZjBjYjViNTVjZGJiMCIsImludGVybmFsX3NlY3JldCI6IjJlYTlkM2Y0LTNiNjktNDU1NS05OWZjLTZiNzdjNWM1MjhmOSJ9.iU-g57BlNbZ3gP61rp_aWL1RSj_umyZ8Phpo5f3zcX8"

